### ISSUE TITLE
Inventory page side bar drop down menus don't close when a different location is clicked

### ISSUE THREAD

**Issue by akshaywari** [biobricks/bionet-new#34] opened 2018-03-06 20:07 UTC
When any of the left side bar buttons on the inventory page are clicked, a drop down menu is loaded. This drop down menu doesn't close unless the button itself is clicked again, instead of closing when anywhere on the page is clicked.

**Comment by autonomous1** [comment] 2018-03-06 20:18
Duplicate of #9

**Closed by autonomous1** 2018-03-06 20:18 UTC
