### ISSUE TITLE
Clicking pencil on inventory page leads to duplication of all buttons on left side

### ISSUE THREAD

**Issue by akshaywari** [biobricks/bionet-new#32] opened 2018-03-06 20:04 UTC
1. Go to inventory page
2. Click pencil button
3. Only thing that happens is the side bar duplicating each time the button is pressed.

**Comment by autonomous1** [comment] 2018-03-06 20:21
Can't reproduce - can you check your console log to see if there are any errors and paste stack trace in comment?

**Comment by autonomous1** [comment] 2018-03-06 20:24
It may have been fixed in another related issue - closing since it cannot be duplicated at this time.

**Closed by autonomous1** 2018-03-06 20:24 UTC
