### ISSUE TITLE
Inventory Edit and Create forms not submitting on enter

### ISSUE THREAD

**Issue by Juul** [biobricks/bionet-new#27] opened 2018-03-06 16:31 UTC
All forms should use the `onsubmit` handler and never the `onclick` handler, otherwise hitting enter in the form won't submit.

**Comment by autonomous1** [comment] 2018-03-06 20:16
Actually, all the forms had the proper onsubmit event handler and submit input controls. The issue was caused by a dropdown menu that was capturing keyboard events. It was fixed by removing e.preventDefault() in the menu dropdown handler.

**Closed by autonomous1** 2018-03-06 20:16 UTC
Labels: bug
