### ISSUE TITLE
Clicking on virtual in search redirects to closed lab tree

### ISSUE THREAD

**Issue by ccmeyer** [biobricks/bionet-new#38] opened 2018-03-08 17:43 UTC
When I click on a plasmid that I search for and it returns a list of physicals I can click on one of those and have it take me to the inventory tree where it will show the location right away but then redirects to the start of the closed tree.

**Comment by autonomous1** [comment] 2018-03-19 06:51
Can't reproduce - seems to be fixed now?

**Closed** 2018-03-22 19:47 UTC
Labels: bug
